#!/usr/bin/env node
// web/scripts/raw-regen.mjs
// Generate player/raw.html by deriving it from calcite.html, so the
// two players share chrome/keyboard verbatim and cannot drift. The
// ONLY differences: the <img> screen becomes a 320x200 = 64000-element
// CSS pixel grid, the cabinet loads as a real stylesheet, .window-body
// gains .clock and .cpu classes to host the cabinet's .cpu-scoped rules,
// and the label reads RAW.
//
// In principle Chrome evaluates the cabinet and the pixel painter
// (kiln/pixels.mjs) drives #p0..#p63999 from the Mode 13h framebuffer.
// In practice Chrome hangs/crashes on the cabinet's size — the point of
// the "raw" player. calcite.html runs the same machine at speed.
//
//   node web/scripts/raw-regen.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const calcitePath = resolve(__dirname, '..', 'player', 'calcite.html');
const outPath = resolve(__dirname, '..', 'player', 'raw.html');

const W = 320, H = 200;

function pixelGrid() {
  const cells = new Array(W * H);
  for (let i = 0; i < cells.length; i++) cells[i] = `<i id="p${i}">`;
  // newline per row keeps editors from choking; grid layout ignores whitespace.
  const rows = [];
  for (let y = 0; y < H; y++) rows.push(cells.slice(y * W, (y + 1) * W).join(''));
  return `<div id="grid" class="screen-grid">\n${rows.join('\n')}\n</div>`;
}

const gridStyle = `  <style>
    /* AUTOGEN raw-player pixel grid — replaces the calcite <img>. */
    .screen-grid {
      display: grid;
      grid-template-columns: repeat(${W}, 2px);
      grid-auto-rows: 2px;
      width: ${W * 2}px;
      height: ${H * 2}px;
      max-width: 640px;
      image-rendering: pixelated;
      background: #000;
      margin: 0 auto;
    }
    .screen-grid > i { display: block; width: 2px; height: 2px; background: transparent; }
  </style>
`;

let html = readFileSync(calcitePath, 'utf8');

// (1) Replace the <img> screen with the pixel grid.
//     The img tag in calcite.html:
//       <img id="calcite-screen"
//            class="screen"
//            src="/_screen/framebuffer"
//            alt=""
//            width="640" height="400">
html = html.replace(
  /<img id="calcite-screen"[\s\S]*?width="640" height="400">/,
  pixelGrid());

// (2) Add .clock and .cpu classes to .window-body so cabinet
//     .cpu-scoped rules (keyboard :has, pixel painter) have a host.
//     Simpler and more robust than wrapping with new divs.
html = html.replace(
  '<div class="window-body">',
  '<div class="window-body clock cpu">');

// (3) Cabinet as a real stylesheet instead of <link rel="alternate">.
html = html.replace(
  '<link rel="alternate" href="/cabinet.css" type="text/css" title="cabinet">',
  '<link rel="stylesheet" href="/cabinet.css">');

// (4) Distinguishing title + label.
html = html.replace(/<title>[^<]*<\/title>/, '<title>CSS-DOS · raw CSS</title>');
html = html.replace('>CALCITE<', '>RAW<');
html = html.replace('CSS-DOS - PLAYING', 'CSS-DOS - RAW CSS');

// (5) Grid geometry styles, injected before </head>.
html = html.replace('</head>', `${gridStyle}</head>`);

// (6) Strip the keyboard hold auto-submit shim — raw stays script-free
//     (the cabinet reads the #kb-X-hold radios directly), and swap the
//     header comment back to the unqualified claim.
html = html.replace(/[ \t]*<!-- kbd-autosubmit -->[\s\S]*?<!-- \/kbd-autosubmit -->\r?\n/, '');
html = html.replace(
  /Pure HTML \+ CSS runner\.[\s\S]*?anywhere\)\./,
  'Pure HTML + CSS runner. No <script> tag anywhere in this file.');
if (/<\/script>/i.test(html)) throw new Error('raw.html still contains a <script> tag');

// Mark the file autogenerated.
html = html.replace('<!DOCTYPE html>',
  `<!DOCTYPE html>\n<!-- AUTOGEN by web/scripts/raw-regen.mjs from calcite.html. Do not edit. -->`);

writeFileSync(outPath, html);
console.log(`raw-regen: wrote ${outPath} (${html.length} bytes, ${W * H} pixels)`);
